version: '3'
services:
  imba97-me:
    image: imba97/me:latest
    container_name: imba97-me
    privileged: true
    ports:
      - '3000:3000'
    restart: always
    environment:
      NAVIDROME_API_URL: ''
      NAVIDROME_USERNAME: ''
      NAVIDROME_PASSWORD: ''
