shellEmulator: true

trustPolicy: no-downgrade

overrides:
  chokidar: ^5.0.0
  semver: 7.7.3
  vite: ^8.0.13

allowBuilds:
  '@parcel/watcher': true
  esbuild: true
  sharp: true
  simple-git-hooks: true
